name: AndroidBuild
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: chmod
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Budle.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build Android Test APK
        run: ./gradlew assembleAndroidTest

      - name: Run Android tests on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: 'android-device.yml:android-pixel-4'
        env:
          SERVICE_ACCOUNT: '{
  "type": "service_account",
  "project_id": "budle-5d393",
  "private_key_id": "0b1d748fd2f278a4c4df01d8f21df3fc3677ceb5",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCUFvfIRVDLD2dW\nZceDX7O7jbL4T65elGb7tER4segCXULHaTmSyXMum4BnjlOzlC34CeqRrjozqEHe\n9vPcUTkNh4dMQgPlvbMj3gNMJTxoPOVSDygXJluRtv8fF7qNEJZ0tYI8pzTOTFIi\n0T+h4NHN66y5/LwUqVpRDMU2E9+eeHKKfjIML/Qjvd70cV00pbA5a79Q5Ua1xYvY\nhto2TIQEeu9IlMPzmmvot4IaQMzDZJY+lt3615XGv5xDrfhCdNwOiVusHlVMmT8U\nHDWnHm7eEhn+8+P5pSWWwBzGFLWGjQTsV53zu5s3T3SVIcU4W/911EZB+1TQ1WXT\nRJ+KoxZVAgMBAAECggEAAR81bFp+FLO+rCxkOQ4SDgMyTmhIIWZNa22/sQxj/hSX\ny2v0KDUHftxluiMdZjhiqsTkdosT3M1TBm3nhg1FeeFDeKPtZKGtyEFH1B1aGk4P\nzLHZs2cyfWWeBC3JV4U/Jo4zeOMpZsC0RJhCO6c4367/5X7RK/TmfsOygMjgwlIT\nVABA7DVLi2b9GXHczIFGNOhaod1eH4ZEMjJoKKz2uGRPeg88ePU0qlZ/GLZDiKra\njCGno0Z14CReXPPOTdSIfgig19KfIfzyFeiVGLtT68GZ9FRSyEjAtzPmhDyOukBV\nnOKrzjbQJyk1fPDTpT/BbJxf2RHJUdzQPXP+494K4QKBgQDL/JlbKlzKAQ5wZNjm\nxnWrFo7WzynZSZd3c7brIOFhVNtZM6ekyzojXp3eTYbihy5yYPLuM/GYBrEArNXW\nFK61I1EAOptiviWlD4YWm419SeZTlTno99x5vrpwdzE4g+Np3D+Ru916hbJFvQww\nVCbyGXucQCpjX3a7edTw9DLapQKBgQC52aV1c6FHKmb850TO7P1hmCH6srcNDytj\nTQqHqVXKl1+369NTIlrOUUy4Dw3VIXUxBX7uhiOHXXMmH2TDPI2GyaSy3UrE3lSg\nicjn+IcRgNL7THOKznZugl8Eqhz/TODYkJeQA/zf/4rNURcVfzLmgEj1kqIUbW8c\nrVvpcA9t8QKBgQCscbeHTVGx56C4PVjsBvw0jVZlnC5JpZ/peKY7Mcm2iZEBYNyp\nQLC+c99LrgiIejU2tmTIIJttpMJ/ypzfZQ6ozNlOMz1nBU43st7tP8UmFJIlOLMD\nEn6NYUKlju3KVBytQmdvIP1D9cBWmlGyjYF7CzXnSotLBMoQBReSNy7CjQKBgCmf\nAXwVQjgi2d+nl3RUBMbXgDyZy37kN85MUaBiHvF5Bxm0eaYzmmx8LpdF384saQdq\neKvIZKqLFh+ihjlnFTbrb7QS9Qyz0fYGBXVV5kHYPOfEjle2tzU2gzsTMd1HBU/a\nyeaZzgcIPriOgYHx859FeZFtnli+zVR5yoyz6PCxAoGANc/nCkSH7TAWsxAg4zhS\n3G761zMEvOa+Wcv1IFuvQ9UzhN7mMbUIB/UtFtTjUGrZMCNfd7ZgcyyqFTHwuBpO\n85XsN3aC3kVeFJTKdrggUYBWaI9NRNKX6SAmx3N+q2Wy6BR2aE8PcP+0S989r7C/\n9BX7EEdTOMgZ5nmmpur0TAA=\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-4glpr@budle-5d393.iam.gserviceaccount.com",
  "client_id": "109811266270670294443",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-4glpr%40budle-5d393.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}'
